version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Docker Credential Helper
          command: |
            sudo apt-get update && sudo apt-get install -y gnupg2 pass
            curl -fsSL https://github.com/docker/docker-credential-helpers/releases/download/v0.6.3/docker-credential-secretservice-v0.6.3-amd64.tar.gz | tar xv -C /tmp
            sudo mv /tmp/docker-credential-secretservice /usr/local/bin/docker-credential-secretservice
            sudo chmod +x /usr/local/bin/docker-credential-secretservice
            mkdir -p ~/.docker && echo '{"credsStore": "secretservice"}' > ~/.docker/config.json
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: echo "No need to install anything. Just build and push the Docker image."
      - run:
          name: Build and push Docker image
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            docker build -t tienhs1234/sample-express-app .        
            docker tag tienhs1234/sample-express-app tienhs1234/sample-express-app:1.0.0
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push tienhs1234/sample-express-app:1.0.0