version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: echo "No need to install anything. Just build and push the Docker image."
      - run:
          name: Build and push Docker image
          command: |
            echo "Inside the Build and push Docker image step"
            docker --version # print the version for logging
            docker build -t sudkul/sample-express-app .        
            docker tag sudkul/sample-express-app sudkul/sample-express-app:1.0.0
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push sudkul/sample-express-app:1.0.0

workflows:
  version: 2
  build:
    jobs:
      - build