version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:19.9.1
    working_directory: ~/app
    environment:
      MY_VAR: "sample-value"
    steps:
      - run: echo $MY_VAR
      - run: node --version
      - run: npm install